DeveloperGuide: update instructions to import project as gradle project
se-edu/addressbook-level25 pull request #147
Opened 2018-08-09 09:14 UTC by yamidark

Part of #146 
```
The instructions for users for setting up of the project Intellij is to
import the project as an existing source.

In order to lessen the learning curve between AB3 and AB4, as well
as to import necessary 3rd party dependencies more easily, we should
update the instructions to import the project as a gradle project.

Let's update the instructions in DeveloperGuide to import the project
into Intellij as a gradle project.
```

2018-08-09 13:39 UTC, pyokagan reviewed
[1/2]

> ```
> build.gradle: add in resources directory
> ```

Maybe `specify resources directory`?

> ```
> When trying to run the app as a gradle project, the app will crash
> with a 'Exception in Application start method'.
> 
> This is due to the resources directory not being specified in
> build.gradle. Thus, Main.class.getResource("ui/mainwindow.fxml") in
> Gui#createMainWindow(Stage, Stoppable) is unable to find the `fxml`
> resource required, causing the app to crash when trying to load a
> null resource.
> 
> Let's update build.gradle to specify the resources directory.
> ```

Yup, this works. I was worried this will cause the JARs to be packaged with the
`.java` source files, but it turns out Gradle will automatically exclude any
files with the `.java` extension from the resources, which is interesting.
(Search for `resources` in
https://docs.gradle.org/current/userguide/java_plugin.html#sec:source_set_properties)

2018-08-09 13:49 UTC, pyokagan reviewed
[2/2]

This works as well, although I hit [this problem with IntelliJ](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000162670-In-2018-1-1-version-Problem-with-Error-cannot-start-process-the-working-directory-idea-modules-does-not-exist-), but it seems like I just need to upgrade my intelliJ installation.

2018-08-09 13:49 UTC, pyokagan commented on docs/DeveloperGuide.adoc
> +. Run the `seedu.addressbook.Main` (right-click the `Main` class and click `Run Main.main()`) and try a few commands
```
Run `seedu.addressbook.Main`
```
or
```
Run the `seedu.addressbook.Main` class
```
?

2018-08-09 13:50 UTC, pyokagan approved these changes
I'm OK with this version, actually.

You can submit another version if you want to fix any nits.

2018-08-09 14:02 UTC, pyokagan commented
Confirmed that it works for me after upgrading to IntelliJ 2018.2.

2018-08-09 14:06 UTC, damithc commented on docs/DeveloperGuide.adoc
> +. Run all the tests (right-click the `test` folder, and click `Run 'All Tests'`) and ensure that they pass
There is a potential problem there though. It slipped my mind earlier. CS2113 and TIC2002 might allow students to stop at AB-3 and also omit CI (at least for weaker teams). Is it possible for those students to do AB-3 without using gradle?

2018-08-09 14:11 UTC, pyokagan commented on docs/DeveloperGuide.adoc
> +. Run all the tests (right-click the `test` folder, and click `Run 'All Tests'`) and ensure that they pass
Possible now, will not be possible from next semester onwards since JavaFX will not be distributed with JDK 11+ any more.

By the way, I actually find it easier to deal with Gradle (no installation needed!) vs IntelliJ and its buggy-ness :-P

2018-08-09 14:16 UTC, damithc commented on docs/DeveloperGuide.adoc
> +. Run all the tests (right-click the `test` folder, and click `Run 'All Tests'`) and ensure that they pass
I see. Never mind. Let's go ahead with this. 👍

2018-08-09 14:49 UTC, yamidark commented on docs/DeveloperGuide.adoc
> +. Run the `seedu.addressbook.Main` (right-click the `Main` class and click `Run Main.main()`) and try a few commands
I will go with `Run the seedu.addressbook.Main class` which sounds better (to me).

2018-08-09 15:26 UTC, Zhiyuan-Amos requested changes
Minor nits 👍

2018-08-09 15:26 UTC, Zhiyuan-Amos commented on docs/DeveloperGuide.adoc
> +. Run the `seedu.addressbook.Main` class (right-click the `Main` class and click `Run Main.main()`) and try a few commands
`try a few commands` doesn't sound that intuitive. Maybe try **executing** a few commands?

2018-08-09 15:26 UTC, Zhiyuan-Amos commented on docs/DeveloperGuide.adoc
>  .. If JDK 8 is listed in the drop down, select it. If it is not, click `New...` and select the directory where you installed JDK 8.
oopsie we're using JDK 9 now right? :P

2018-08-09 15:34 UTC, yamidark commented on docs/DeveloperGuide.adoc
>  .. If JDK 8 is listed in the drop down, select it. If it is not, click `New...` and select the directory where you installed JDK 8.
This is a prerequisite before we upgrade the JDK9, which will be done in another PR.

2018-08-10 00:07 UTC, Zhiyuan-Amos approved these changes

2018-08-10 05:37 UTC, damithc approved these changes

2018-08-11 06:15 UTC, merged