Ensure Java 9 compatibility #146
se-edu/addressbook-level25 pull request #148
Opened 2018-08-11 06:19 UTC by yamidark

Fixes #146 
```
The project currently runs on Java 8.

Since AddressBookL4 is already running on Java 9, this project should
be upgraded to run on Java 9 as well for consistency.

Let's upgrade the project to run on Java 9 and update the
documentation accordingly.

Travis currently builds the project using JDK 8. Since we are now
running on Java 9, let's update it to build the project using JDK 9.

Java 9 introduces a module system. By default, the set of root modules
for unnamed modules is based on the java.se module instead of the
java.se.ee modules. Thus, APIs in modules from the java.se.ee module,
such as java.xml.bind, are not accessible by default[1]. As our project
is still an unnamed module which depends on the java.xml.bind module,
it is no longer compilable. To resolve this, let's update build.gradle
to import the dependencies for java.xml.bind.

UtilsTest uses the Integer(int) constructor for its equality test,
which is deprecated from Java 9[2]. Since use of deprecated APIs is
considered bad practice, let's replace this with Integer.valueOf(int).

[1]: http://openjdk.java.net/jeps/261
[2]: https://docs.oracle.com/javase/9/docs/api/java/lang/Integer.html#Integer-int-
```

2018-08-11 07:44 UTC, yamidark commented
According to this [issue](https://youtrack.jetbrains.com/issue/IDEA-189060) with some of the newer Intellij versions, even though the JAXB dependencies have been imported through gradle, and the code compiles and runs successfully, the IDE will still 'detect' and show code errors in these files (same problem occuring in AB4 as well). 
@pyokagan @yamgent @Zhiyuan-Amos Can help verify this on your side as well?

This will probably cause confusion to the students. Should we add a note of this error in the setting up of project in DeveloperGuide, and a way to remove the code error warnings?

![untitled](https://user-images.githubusercontent.com/18352498/43989458-f2c82b9c-9d7c-11e8-9093-c8baec4c9bb3.png)

2018-08-11 12:19 UTC, yamgent commented
Mine didn't show that error. (version: `IntelliJ IDEA 2018.2.1 (Community Edition)`)

Nevertheless, if multiple people have this issue, you can add in under a "Frequent Problems" section or something similar in the developer guide.

2018-08-11 14:12 UTC, yamidark commented
Hmm, seems to just be an issue with `Ultimate Edition`, tried `Standard Edition` and there were no errors.
Will add a "Troubleshooting" section at the bottom just in case.

2018-08-12 05:54 UTC, Zhiyuan-Amos reviewed
[2/2] Missing hyperlink in commit message for footnote 1.

Also note that it's Intelli**J** :P

Spelling error for depende**n**cies

2018-08-12 05:54 UTC, Zhiyuan-Amos commented on docs/DeveloperGuide.adoc
> +Solution: Place your cursor over any of the code section highlighted in red. Press ALT + ENTER, and select `Add '--add-modules java.xml.bind' to module compile options`. The code errors should no lon
Should ALT + ENTER be codified i.e. `ALT + ENTER`?

2018-08-12 05:54 UTC, Zhiyuan-Amos commented on docs/DeveloperGuide.adoc
> +Solution: Place your cursor over any of the code section highlighted in red. Press ALT + ENTER, and select `Add '--add-modules java.xml.bind' to module compile options`. The code errors should no lon
Should we format this according to [AB-Level 4](https://github.com/se-edu/addressbook-level4/blob/master/docs/DeveloperGuide.adoc#53-troubleshooting-testing)?

2018-08-12 05:58 UTC, Zhiyuan-Amos reviewed
[1/2]

```
UtilsTest uses the Integer(int) constructor for its equality test,
which is deprecated from Java 9[1]
```

I can't find in the hyperlink that `Integer(int)` constructor is deprecated from Java 9 tho :o

2018-08-12 06:05 UTC, yamidark commented on docs/DeveloperGuide.adoc
> +Solution: Place your cursor over any of the code section highlighted in red. Press ALT + ENTER, and select `Add '--add-modules java.xml.bind' to module compile options`. The code errors should no lon
It wasn't codified in AB2 DG, so guess don't need to here

2018-08-12 06:21 UTC, Zhiyuan-Amos commented on docs/DeveloperGuide.adoc
> +Solution: Place your cursor over any of the code section highlighted in red. Press ALT + ENTER, and select `Add '--add-modules java.xml.bind' to module compile options`. The code errors should no lon
Yup just saw that too, ok! 👍

2018-08-12 07:20 UTC, Zhiyuan-Amos approved these changes
Minor nit, after this it's good to go 👍 great effort for finding the links!

2018-08-12 07:20 UTC, Zhiyuan-Amos commented on docs/DeveloperGuide.adoc
> +**Problem: IntelliJ is reporting code errors in `StorageFile`, but the project can be build and run successfully.**
can be buil~~d~~**t**

2018-08-12 08:24 UTC, damithc reviewed
A query

2018-08-12 08:24 UTC, damithc commented on docs/DeveloperGuide.adoc
> +
We can add this as an additional step in the step-by-step guide. i.e., ask the user to check for this problem at the appropriate step and resolve it _if_ necessary (as this may get resolved in future versions of IDEA). What do you think?

2018-08-12 09:27 UTC, yamidark commented on docs/DeveloperGuide.adoc
> +
Hmm, we can ask them to check for this in the last step, as this shouldn't be a solution to failing builds/tests, if the project was imported correctly as a gradle project.

2018-08-12 09:57 UTC, damithc commented on docs/DeveloperGuide.adoc
> +
Sure.

2018-08-12 12:57 UTC, yamgent commented
> This will probably cause confusion to the students. Should we add a note of this error in the setting up of project in DeveloperGuide, and a way to remove the code error warnings?

While porting the tutorial in https://github.com/se-edu/se-book/pull/62, I spotted the same error. Instead of the <kbd>Alt</kbd>+<kbd>Enter</kbd> trick, I used `module-info.java` to solve the issue.

Strangely enough, <kbd>Alt</kbd>+<kbd>Enter</kbd> does not seem to suggest modifying `module-info.java`. Maybe at this stage not many people use modules, thus that recommendation might not have been implemented yet 🤔.

2018-08-12 14:13 UTC, yamidark commented
>Strangely enough, Alt+Enter does not seem to suggest modifying module-info.java. Maybe at this stage not many people use modules, thus that recommendation might not have been implemented yet 

Tried adding an empty `module-info.java`, and the <kbd>Alt</kbd> + <kbd>Enter</kbd> does suggest adding this to `module-info.java` (on my side).

However, adding the `module-info.java` with all the required dependencies instead cause the program to crash with:
`Package seedu.addressbook.storage.jaxb with JAXB class seedu.addressbook.storage.jaxb.AdaptedAddressBook defined in a module addressbook.level3 must be open to at least java.xml.bind module.`

@yamgent Does your code build and run with the added `module-info.java`?

2018-08-12 15:17 UTC, yamgent commented
> Package seedu.addressbook.storage.jaxb with JAXB class seedu.addressbook.storage.jaxb.AdaptedAddressBook defined in a module addressbook.level3 must be open to at least java.xml.bind module.

This means that it expects an `opens` statement for `seedu.addressbook.storage.jaxb`:

```java
module addressbook.level3.main {
    requires java.xml.bind;
    requires javafx.fxml;
    requires javafx.graphics;
    requires javafx.controls;

    opens seedu.addressbook.storage.jaxb to java.xml.bind;
}
```

I tried fixing the errors but eventually end up in a runtime error (can be traced to some JAXB problem, seems like that is not getting exported properly? maybe that has to do with the errors that we are getting on Travis?).

If we are running out of time, the <kbd>Alt</kbd>+<kbd>Enter</kbd> can be an acceptable alternative.

2018-08-13 13:07 UTC, yamidark commented
>I tried fixing the errors but eventually end up in a runtime error (can be traced to some JAXB problem, seems like that is not getting exported properly

I tried debugging this too, seems like its the same error as I mentioned in https://github.com/se-edu/addressbook-level3/commit/b72eec207cef33fe279262f69fe290b84ac581eb, for some reason it is unable to get the resource `main.window.fxml`. Currently trying to find a way to resolve this...

2018-08-21 11:04 UTC, yamidark commented
@yamgent 
Managed to somewhat find the problem with this...

So when a `-module-info.java` is specified, IntelliJ will run using the 'modulepath' instead of 'classpath', which is set to `out/production/classes`. However, gradle places the resources in `out/production/resources`, thus the program is unable to find the resources and returns `null` for `Class.getResource`. 

There was also a need to `opens` the 'ui' package to `javafx.fxml` so that the `MainWindow` becomes accessible, and after that changing the location of the `Darktheme.css` in `mainwindow.fxml` to `@Darktheme.css` instead (since it searched relative to the opened 'ui' package instead?).

However, I couldn't really get to specify the output of the resources to be in the same module path, even after specifying `output.resourceDirs` in gradle, so I'm still somewhat stuck here.

2018-08-21 11:39 UTC, pyokagan commented
Gradle doesn't have first-class support for Java modules (development seems to be slow upstream as well). I suppose trying to convert the project to use Java modules without its support would be an uphill battle.

2018-08-21 11:41 UTC, pyokagan commented
We could try using https://github.com/zyxist/chainsaw for fun, just to see what happens, but I don't think the results should be committed into master.

2018-08-21 11:47 UTC, pyokagan commented
> However, gradle places the resources in out/production/resources, thus the program is unable to find the resources and returns null for Class.getResource.

This statement seems weird, btw. Gradle is writing to `out/`??? I thought only IntellIJ did that.

2018-08-21 12:02 UTC, yamidark commented
>This statement seems weird, btw. Gradle is writing to out/??? I thought only IntellIJ did that.

Whoops, sorry, meant to say IntelliJ does that when we import as a gradle project 💦.

2018-08-21 14:08 UTC, yamgent commented
@yamidark If you go to `File` -> `Project Structure` -> `Modules` -> `addressbook-level3_main` -> `Paths`, and select "Inherit project compile output path", does it work?

2018-08-21 14:46 UTC, yamidark commented
>If you go to File -> Project Structure -> Modules -> addressbook-level3_main -> Paths, and select "Inherit project compile output path", does it work?

Yep, it works! 👍.

2018-08-21 14:55 UTC, pyokagan commented
@yamgent One thing before you proceed with this though: make sure that the same approach works for AB-4 (and whether e.g. `./gradlew run` still works or not over there once there is a `module-info.java` file).

2018-08-28 08:34 UTC, yamidark commented
@yamgent @pyokagan 

Managed to configure the `module-info.java` and `build.gradle` get it to run and all the tests to pass in AB-4 along with gradle, but IntelliJ still has some issues.

In IntelliJ, there was still a runtime error when trying to run the app, 
`impl.org.controlsfx.version.VersionChecker (in module controlsfx) cannot access class com.sun.javafx.runtime.VersionInfo (in module javafx.base) because module javafx.base does not export com.sun.javafx.runtime to module controlsfx`.
The only solution I managed to find for this would be to add 
`--add-exports=javafx.base/com.sun.javafx.runtime=controlsfx` to the VM arguments.

Also, the test classes will still have the same problem where `java.xml.bind` has code errors (although we can run tests normally), since it doesn't have a `module-info.java`, and I'm unable to add it in because of [split packages](https://www.logicbig.com/tutorials/core-java-tutorial/modules/split-packages.html).

From this, I believe that trying to use Java modules compared to just <kbd>Alt</kbd> + <kbd>Enter</kbd> to resolve this issue is really overkill and also too troublesome for the students.

2018-08-28 12:14 UTC, yamgent commented
> From this, I believe that trying to use Java modules compared to just Alt + Enter to resolve this issue is really overkill and also too troublesome for the students.

Ok, let's just use <kbd>Alt</kbd>+<kbd>Enter</kbd> then, it is still in some sense using the module system, while still providing a simple fix for the problem.

2018-08-28 13:32 UTC, pyokagan commented
I agree it would be ideal if the ABs could be migrated to the module system, but it seems that the ecosystem has not caught up yet.

@yamidark Maybe you could submit a PR with your work to AB-4? Might be useful in the future when it's time to migrate.  If your commits are polished enough we could possibly just use your work as-is and keep your authorship, so your efforts won't get wasted.

2018-08-29 11:27 UTC, yamgent approved these changes

2018-08-29 14:35 UTC, damithc approved these changes

2018-08-30 12:52 UTC, pyokagan commented
@yamidark 

> ```
> Java 9 introduces a module system, causing internal packages such as
> javax.* and com.sun.* packages to be inaccessible[1].
> 
> ...
> 
> [1]: http://openjdk.java.net/jeps/260
> ```

From my understanding, it is more to do with the fact that (1) AB-3 is an unnamed module since it does not have a `module-info.java`, and (2) the `java.xml.bind` module is not part of the default set of root modules for unnamed modules?

So, http://openjdk.java.net/jeps/261 would be a better link? Specifically since it mentions:

> The default set of root modules for the unnamed module is based upon the java.se module rather than the java.se.ee module. Thus, by default, code in the unnamed module will not have access to APIs in the following modules:
> 
> ```
> java.activation
> java.corba
> java.transaction
> java.xml.bind
> java.xml.ws
> java.xml.ws.annotation
> ```

2018-08-30 16:27 UTC, yamidark commented
@pyokagan 
>From my understanding, it is more to do with the fact that (1) AB-3 is an unnamed module since it does not have a module-info.java, and (2) the java.xml.bind module is not part of the default set of root modules for unnamed modules?
So, http://openjdk.java.net/jeps/261 would be a better link?

Sounds good 👍. Will edit the message.

2018-08-31 05:01 UTC, pyokagan commented
@yamidark 

> ```
> Java 9 introduces a module system, causing internal packages such as
> java.xml.bind to be inaccessible to unnamed modules by default[1]. As
> ```


Just to check again: is it really true that `java.xml.bind` is an internal API? Or is it just not accessible by default just because it is a Java EE package?

http://openjdk.java.net/jeps/261 says that "Modules that define Java EE APIs, or APIs primarily of interest to Java EE applications, have been deprecated and will be removed in a future release. They are not resolved by default for code on the class path", so I'm leaning towards the latter. I don't really think it has anything to do with internal APIs as well.

(Because, if we are really using an internal API, I think we have a bigger problem ;-) )


Also, a nit: http://openjdk.java.net/jeps/261 says that:

"""This is an intentional, if painful, choice, driven by two goals:

* To avoid unnecessary conflicts with popular libraries that define types in some of the same packages. The widely-used jsr305.jar, e.g., defines annotation types in the javax.annotation package, which is also defined by the java.xml.ws.annotation module.

* To make it easier for existing application servers to migrate to JDK 9. Application servers often override the content of one or more of these modules, and in the near term they are most likely to do so by continuing to place the necessary non-modular JAR files on the class path. If these modules were resolved by default then the maintainers of application servers would have to take awkward actions to exclude them in order to override them."""

So I'd say this is a decision made independently of the module system (i.e. the module system doesn't directly "cause" this, it is possible for the `java.se.ee` module to be part of the root set of modules, it is just that they explicitly chose not to), so we shouldn't say it is `causing`?

2018-09-01 17:56 UTC, yamidark commented
@pyokagan 

>Just to check again: is it really true that java.xml.bind is an internal API? Or is it just not accessible by default just because it is a Java EE package?
http://openjdk.java.net/jeps/261 says that "Modules that define Java EE APIs, or APIs primarily of interest to Java EE applications, have been deprecated and will be removed in a future release. They are not resolved by default for code on the class path", so I'm leaning towards the latter. I don't really think it has anything to do with internal APIs as well.

Yes, your right. Seems I mixed up public and internal APIs together. Will update my commit message.

>So I'd say this is a decision made independently of the module system (i.e. the module system doesn't directly "cause" this, it is possible for the java.se.ee module to be part of the root set of modules, it is just that they explicitly chose not to), so we shouldn't say it is causing?

True, seems I picked the wrong choice of words 😓.

2018-09-02 06:32 UTC, pyokagan commented
@yamidark Thanks for the clarification.

The new Java module system is quite complex, so the clarity is needed to ensure we are fixing the right thing :-)

2018-09-02 06:39 UTC, pyokagan requested changes
One more thing.

2018-09-02 06:39 UTC, pyokagan commented on docs/DeveloperGuide.adoc
> +.. Due to an ongoing https://youtrack.jetbrains.com/oauth?state=%2Fissue%2FIDEA-189060[issue] with some of the newer versions of IntelliJ, code errors may be detected even if the project can be built
The link should be https://youtrack.jetbrains.com/issue/IDEA-189060 . "oauth" seems to be some kind of internal authorization URL, and so would be less likely to have any guarantees of permanence.

Same for the commit message.

2018-09-02 09:43 UTC, pyokagan approved these changes

2018-09-02 09:45 UTC, merged