LearningOutcomes: fix broken links
se-edu/addressbook-level25 pull request #150
Opened 2018-08-12 05:33 UTC by yamidark

```
In LearningOutcomes, some of the links are broken.

Let's fix them.
```

2018-08-12 05:49 UTC, Zhiyuan-Amos requested changes
Changes requested :P

2018-08-12 05:49 UTC, Zhiyuan-Amos commented on docs/LearningOutcomes.adoc
> +* https://se-edu.github.io/se-book/oop/abstractClasses/[se-edu/se-book: Implementation: OOP: Abstract Classes]
Link should be: https://se-edu.github.io/se-book/oop/inheritance/abstractClasses/

2018-08-12 05:49 UTC, Zhiyuan-Amos commented on docs/LearningOutcomes.adoc
> +* https://se-edu.github.io/se-book/oop/interfaces/[se-edu/se-book: Implementation: OOP: Abstract Interfaces]
Link should be: https://se-edu.github.io/se-book/oop/inheritance/interfaces/

2018-08-12 05:53 UTC, yamidark commented on docs/LearningOutcomes.adoc
> +* https://se-edu.github.io/se-book/oop/interfaces/[se-edu/se-book: Implementation: OOP: Abstract Interfaces]
Whoops, forgot to check the `oop` links 😓

2018-08-12 07:21 UTC, Zhiyuan-Amos approved these changes
👍

2018-08-12 08:25 UTC, damithc reviewed
There might be additional links to add at these places. I'll get back in 1-2 days. Remind me if I don't.

2018-08-15 05:35 UTC, yamidark commented
@damithc 
>There might be additional links to add at these places. I'll get back in 1-2 days. Remind me if I don't.

May I know if there are any additional links to add?

2018-08-15 06:46 UTC, damithc commented
Additional references to add:
* LO-Polymorphism https://se-edu.github.io/se-book/cppToJava/inheritance/polymorphism/index.html
* LO-Abstract https://se-edu.github.io/se-book/cppToJava/inheritance/abstractClassesAndMethods/index.html
* LO-Interfaces https://se-edu.github.io/se-book/cppToJava/inheritance/interfaces/index.html

That's all. :-)

2018-08-15 07:56 UTC, Zhiyuan-Amos approved these changes

2018-08-15 09:04 UTC, damithc approved these changes

2018-08-16 14:48 UTC, merged