Set up Travis CI #45
se-edu/addressbook-level25 pull request #64
Opened 2017-01-20 08:45 UTC by MightyCupcakes

Closes #45 

This gradle build file is the bare minimum for travis CI and thus will not support the building of jar file using `gradlew build` as it requires the bundling of the wrapper file and additional plugins which is not the aim of this PR.

2017-01-20 09:47 UTC, damithc commented
Enabled Travis for this repo (to verify this PR). Going to close-open to trigger a build.

2017-01-21 08:55 UTC, yamgent commented
Should we consider printing the name of each test case, just like in [se-edu/addressbook-level4#258](https://github.com/se-edu/addressbook-level4/pull/258#issuecomment-274112933)?

2017-01-21 13:54 UTC, MightyCupcakes commented
Yes, it is a good idea since I had to intentionally fail some tests while setting up this PR to make sure tests are indeed running. I have implemented it.

2017-01-21 14:11 UTC, yamgent approved these changes
Looks good.

2017-01-21 14:23 UTC, damithc reviewed
1. Use CanIHasReview
2. Improve commit message (describe WHY aspect: explain rationale for having the checkstyle, the decision on verbosity level, etc.)

2017-01-21 14:45 UTC, MightyCupcakes commented
This PR does not implement checkstyle. It will only set up enough for the travis CI service to test all future PRs.

Regardless, I have refactored the commit message to include the rationale for implementing an CI service on this repo.

2017-01-22 01:47 UTC, damithc requested changes

2017-01-22 01:47 UTC, damithc commented on build.gradle
> +}
Is there a way to add comments to gradle files? In that case we may want to explain the code in the file itself.

2017-01-22 02:29 UTC, MightyCupcakes commented
Added comments to the gradle file to explain the purpose of the added code in the latest iteration.

2017-01-22 02:31 UTC, damithc approved these changes

2017-01-22 02:31 UTC, damithc commented
@m133225 any input?

2017-01-24 05:45 UTC, m133225 requested changes
Sorry for the delay. I do think that the comments are not concise enough. Perhaps we can just copy-paste from the [level4#258](https://github.com/se-edu/addressbook-level4/pull/258)'s comments? i.e. change it to the following:
`
Prints the currently running test's name in the CI's build log, so that we can check if tests are being silently skipped or stalling the build.
`

2017-01-28 07:56 UTC, damithc commented
@m133225 for your comments

2017-01-30 06:43 UTC, m133225 approved these changes

2017-01-30 07:49 UTC, merged