Migrate project to use IntelliJ instead of Eclipse #83
se-edu/addressbook-level25 pull request #84
Opened 2017-08-16 01:27 UTC by yamgent

Fixes #83.

2017-08-16 01:34 UTC, yamgent commented on doc/DeveloperGuide.md
> +    1. Ensure that you have run all the tests cases (if not, right-click the `test` folder, and click `Run 'All Tests'`)
Had to indent one more space, because GitHub doesn't render this inner list properly otherwise.

2017-08-16 02:24 UTC, damithc requested changes

2017-08-16 02:24 UTC, damithc commented on doc/DeveloperGuide.md
> +    1. Ensure that you have run all the tests cases (if not, right-click the `test` folder, and click `Run 'All Tests'`)
There is a separate section for testing later in this doc, which is still written for Eclipse BTW. Do a project-wide search for `Eclipse` to be safe.

2017-08-16 14:20 UTC, yamgent commented on doc/UserGuide.md
> +  [set command line parameters before running the program](https://stackoverflow.com/a/2066465).
On a side note, I don't think we have this feature in `addressbook-level3`. I looked around the code and there is nowhere that reads in the command line parameter and pass that into `StorageFile(String filePath)`.

2017-08-16 14:22 UTC, yamgent commented
Also should we update [LearningOutcomes.md](https://github.com/se-edu/addressbook-level3/blob/master/doc/LearningOutcomes.md#use-java-fx-for-gui-programming-lo-javafx) to point to the tutorial's intelliJ version?

2017-08-16 14:56 UTC, damithc commented on doc/UserGuide.md
> +  [set command line parameters before running the program](https://stackoverflow.com/a/2066465).
Can remove in that case.

2017-08-16 14:56 UTC, damithc commented
> Also should we update LearningOutcomes.md to point to the tutorial's intelliJ version?

Yup.

2017-08-17 01:48 UTC, yamgent commented on doc/UserGuide.md
> +  [set command line parameters before running the program](https://stackoverflow.com/a/2066465).
Ok, I also created issue #85 about this.

2017-08-17 14:51 UTC, damithc requested changes
Looks good. Just a couple of cosmetic suggestions.

2017-08-17 14:51 UTC, damithc commented on doc/DeveloperGuide.md
> +    1. Ensure that you have run all the tests cases (if not, right-click the `test` folder, and click `Run 'All Tests'`)
This sentence comes as a surprise. Is running test cases part of the set up process.  I don't see any instructions to that effect prior to this sentence.

2017-08-17 14:51 UTC, damithc commented on doc/LearningOutcomes.md
> +* [JavaFX 8 Tutorial](https://se-edu.github.io/se-book/javaTools/javaFXBasic/) adapted with permission from Marco Jakob
No need to mention `adapted with permission from Marco Jakob` here as it is already mentioned in the tutorial itself.

2017-08-19 03:53 UTC, damithc commented on doc/DeveloperGuide.md
> +5. Click `OK`
How about this? 
```
10. Run all the tests (right-click the `test` folder, and click `Run 'All Tests'`)
11. Observe how some tests fail. That is because they try to access the test data from the wrong directory (the working directory is expected to be the root directory, but IntelliJ runs the test with `test\` as the working directory by default). To fix this issue:
  1. Go to `Run` -> `Edit Configurations...`
  2. On the list at the left, ensure that `All in test` is selected
  3. Under `Configuration`, change the `Working directory` to the `addressbook-level3` folder
  4. Click `OK`
12. Run the tests again to ensure they all pass now.
```

2017-08-19 06:37 UTC, damithc approved these changes

2017-08-19 16:17 UTC, merged